### ISSUE TITLE
read .pyc

### ISSUE THREAD

**Issue by Majingnan36** [MatthieuDartiailh/bytecode#123]
Does it support reading .pyc files? Get all bytecode instructions in .pyc by similar to Bytecode.from_code(code_obj)

**Comment by MatthieuDartiailh** [comment]
No currently bytecode only operate on code objects. 

I never tried to open a pyc and unmarshall it, but you could try that and grab the module code object to use with bytecode.

**Comment by P403n1x87** [comment]
Would something like this work for you?

```python
from pkgutil import read_code

with open("path/to.pyc", "rb") as f
    bc = Bytecode.from_code(read_code(f))
```

**Comment by Majingnan36** [comment]
Thanks for your answers, it's very helpful for me
