### ISSUE TITLE
Bytecode doesn't properly set linenumbers (in corner case in Python 3.10rc1)

### ISSUE THREAD

**Issue by fabioz** [MatthieuDartiailh/bytecode#84]
For some context, I use bytecode to set programmatic breakpoints in the pydev debugger and while using it with Python 3.10, I found a corner case where the line isn't being properly mapped back to bytecode.

-- note that it works in Python 3.9 and it also works if the target file is a bit different -- say with less lines or with smaller lines -- so, it seems I got extremely lucky that I have a test case which got into this situation...

I'm attaching a test case which shows the issue. What the test does is load the code for a function (in this case `long_lines_example.long_lines`) and change the 2nd line of that function to include bytecode which does something as the code below and generates back a code object:

```
    label = Label()
    return [
        # -- if _pydev_needs_stop_at_break():
        Instr("LOAD_CONST", _pydev_needs_stop_at_break, lineno=stop_at_line),
        Instr("LOAD_CONST", stop_at_line, lineno=stop_at_line),
        Instr("CALL_FUNCTION", 1, lineno=stop_at_line),
        Instr("POP_JUMP_IF_FALSE", label, lineno=stop_at_line),

        #     -- _pydev_stop_at_break()
        #
        # Note that this has line numbers -1 so that when the NOP just below
        # is executed we have a spurious line event.
        Instr("LOAD_CONST", _pydev_stop_at_break, lineno=stop_at_line - 1),
        Instr("LOAD_CONST", stop_at_line, lineno=stop_at_line - 1),
        Instr("CALL_FUNCTION", 1, lineno=stop_at_line - 1),
        Instr("POP_TOP", lineno=stop_at_line - 1),

        # Put NOP in new line so that Python given a line event for the debugger.
        Instr("NOP", lineno=stop_at_line),
        label,
    ]
```

This works well enough in general, but for this specific use case in Python 3.10 it's not putting the `NOP` in a new line.

[test_bytecode_line_not_correct.zip](https://github.com/MatthieuDartiailh/bytecode/files/7139096/test_bytecode_line_not_correct.zip)

Any ideas on what may be wrong there?

**Comment by MatthieuDartiailh** [comment]
Python 3.10 changed the encoding of the line numbers so I may have gotten that corner case wrong. The relevant section for writing bytecode is https://github.com/MatthieuDartiailh/bytecode/blob/ccb8a7b4bf12a85ff53c3c42517d2633c5225829/bytecode/concrete.py#L303

Another thing to keep in mind is that 3.10 started to allow bytecode with no line number and I did not check if those round tripped properly.

**Comment by fabioz** [comment]
I'm investigating.

As a note, apparently it's wrong before getting to the `_assembly_linestable` (the lines in memory seem to be off already right after loading the bytecode).
