### ISSUE TITLE
Please clarify the copyright

### ISSUE THREAD

**Issue by juliangilbey** [MatthieuDartiailh/bytecode#90]
Hi!

I was looking for copyright information for this package (planning to package it for Debian), and got stuck.
`doc/conf.py` states: `copyright = u"2016-2021, Victor Stinner"` while `COPYING` says: `Copyright (c) 2016 Red Hat.`

These cannot both be correct!  My guess is that `COPYING` should be changed.  Also, the `setup.py` file says that the author is Victor Stinner and the maintainer is Matthieu C. Dartiailh; do both of you share the copyright, or does Victor hold the copyright alone, even though you took over the package in 2017?

(BTW, `u"..."` can be replaced with just `"..."` throughout the `doc` directory, as the Unicode marker is unnecessary in Python 3.)

Thanks for this package!

**Comment by MatthieuDartiailh** [comment]
From my point of view the author/maintainer fields are correct since I did not create the library. However I am rather clueless when it comes to copyright. @vstinner could you enlighten me, in particular when it comes to how Red Hat fits in the picture ?

**Comment by vstinner** [comment]
Bytecode was my personal project, I likely blindly copied COPYING from another project without paying attention to what it says.

As a french person, I don't understand these copyright things. In France, it's very different.

I would prefer to change the copyright to ``Copyright Contributors to the bytecode project``.

**Comment by vstinner** [comment]
I wrote https://github.com/MatthieuDartiailh/bytecode/pull/91 to fix it.

**Comment by MatthieuDartiailh** [comment]
#91 is merged so closing this.
