### ISSUE TITLE
Remove `Compare.EXC_MATCH` on Python>=3.9

### ISSUE THREAD

**Issue by P403n1x87** [MatthieuDartiailh/bytecode#93]
Python 3.9 introduced the `JUMP_IF_NOT_EXC_MATCH` opcode, and the use of `Compare.EXC_MATCH` produces bad code that results in
~~~
TypeError: 'UH��H��]�l�' not supported between instances of 'type' and 'type'
~~~
therefore I would like to suggest that the attribute `Compare.EXC_MATCH` be defined only under the condition `sys.version_info[:2] < (3, 9)`

**Comment by MatthieuDartiailh** [comment]
Sounds perfectly reasonable. Please make a PR.
